apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: spring-boot-app
        image: shan123456/shantanu:replaceImageTag
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: my-dockerhub-secret
